apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# this will over-write the namespace all the resourses will be deployed to
namespace: vault

resources:
  - ../../base

patchesStrategicMerge:
  - namespace.yaml

# list the helm chart we want to 
helmCharts:
  - name: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    version: 0.22.0
    valuesFile: values.yaml

secretGenerator:
  - name: vault-kms
    env: .env

generatorOptions:
  disableNameSuffixHash: true