apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tooling

labels:
  - pairs:
      env: dev-tooling
    includeSelectors: true

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
  - deployment.yaml

images:
- name: dareyregistry/tooling-app
  newTag: "0.2"
  newName: onyekaonu/nginx-onyeka-app
