apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-dev
bases:
  - ../../base

commonLabels:
  env: dev-app

resources:
- namespace.yaml

patches:
- replica-count.yaml
 
configMapGenerator:
- name: website-index-file
  # behavior: replace
  files:
  - index-file

patchesStrategicMerge:
- env.yaml

images:
- name: nginx
  newTag: perl