name: Deploy to Aurora

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MySQL client
      run: sudo apt-get install -y mysql-client

    - name: Run SQL script
    #   env:
    #     AURORA_ENDPOINT: ${{ secrets.AURORA_ENDPOINT }}
    #     DB_USER: ${{ secrets.DB_USER }}
    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #     DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        mysql -h database-1-instance-1.cjcae2iy0tn9.us-east-2.rds.amazonaws.com -u onyekaonu -ponyekaonu toolingdb < tooling_db_schema.sql
        # mysql -h $AURORA_ENDPOINT -u $DB_USER -p$DB_PASSWORD $DB_NAME < tooling_db_schema.sql
